site_title = "LibSignal-SignalArxiv"
limit_days = 7
cache_url = "https://github.com/wingsweihua/review-meetings/cache.json"

[[sources]]
limit = 150
category = "IIS"
title = "Information and Intelligent Systems"

[[sources]]
limit = 150
category = "CCF"
title = "Computing & Communication Foundations"

[[sources]]
limit = 150
category = "CNS"
title = "Computer and Network Systems"


[[sources]]
limit = 150
category = "OAC"
title = "Cyberinfrastructure"


[[sources]]
limit = 150
category = "CMMI"
title = "Civil, Mechanical, and Manufacturing Innovation"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_contact.rhai"
highlight_conference = "scripts/highlight_time.rhai"
